name: Pack Help.zip
on:
  push:
    paths: '**/**'
  workflow_dispatch:

jobs:
  update-help:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack
        run: |
            rm -f * || true
            rm -r .github
            zip -r Help.zip ./
            ls

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Help
          path: Help.zip

      - uses: actions/checkout@v4
        with:
          repository: PCL-Community/PCL2-CE

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          path: 'Plain Craft Launcher 2/Resources'

      - name: Git
        run: |
            ls "Plain Craft Launcher 2/Resources"