name: Pack Help.zip
on:
  push:
    paths: '**/**'
  workflow_dispatch:

jobs:
  update-help:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack
        run: |
            rm -f * || true
            rm -r .github
            ls
            zip -r Help.zip ./

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Help
          path: Help.zip